<?xml version="1.0" encoding="utf-8"?><Database Name="QuantitySQL" Class="QuantityFoxDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\QuantitySQL.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="huntingFoxes.Properties.Settings" SettingsPropertyName="QuantitySQLConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.QuantityFoxes" Member="QuantityFoxes">
    <Type Name="QuantityFoxes">
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Key]" Member="Key" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>